test_task:
  container:
    image: node:latest
  always:
    yarn_cache:
      folder: node_modules
      fingerprint_script: |
        cat package.json
        cat yarn.lock
      populate_script: yarn
  test_script: yarn test

deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  env:
    DEPLOY_TOKEN: ENCRYPTED[d0b60a11a693454be3eaffcf678f90d6d574902d85ae22432e8c5017181c6e45ee10bf56041ab3af605e39c1d7f6274e]
  container:
    image: node:latest
  always:
    yarn_cache:
      folder: node_modules
      fingerprint_script: |
        cat package.json
        cat yarn.lock
      populate_script: yarn
  deploy_script: |
    yarn deploy-clean
    git remote set-url origin https://RDIL:${DEPLOY_TOKEN}@github.com/RDIL/Reeces-Timer.git
    git config user.name "Cirrus CI"
    git config user.email "support@rdil.rocks"
    yarn deploy
